name:                database
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/gbwey/database#readme
license:             BSD3
copyright:           2018 grant weyburne
category:            Database

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - contravariant
  - deepseq
  - dhall >= 1.32.0
  - shakespeare
  - template-haskell
  - text

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wunused-type-patterns
  - -Wredundant-constraints
  - -Wnoncanonical-monad-instances
  - -Wmonomorphism-restriction
  - -Wmissing-deriving-strategies
  - -Wmissing-local-signatures
  - -Widentities
  - -Wmissing-export-lists

tests:
  database-test:
    main:                Main.hs
    source-dirs:
#    - src
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wunused-type-patterns
    - -Wredundant-constraints
    - -Wmissing-deriving-strategies
    - -Widentities
    - -Wno-missing-export-lists
    - -Wno-missing-local-signatures
    dependencies:
    - database
    - tasty
    - tasty-hunit
